# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy all project files from the browserbase directory (since dockerBuildPath is set to browserbase, context is already the browserbase folder)
COPY . .

# Install dependencies without executing prepare scripts
RUN npm install --ignore-scripts

# Build the project
RUN npm run build

# Set entrypoint to start the MCP server
ENTRYPOINT ["node", "dist/index.js"]
